const { environment } = require('@rails/webpacker')
const svelte = require('./loaders/svelte')
const coffee =  require('./loaders/coffee')
const erb =  require('./loaders/erb')
const elm =  require('./loaders/elm')
const typescript =  require('./loaders/typescript')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)
environment.loaders.prepend('typescript', typescript)
environment.loaders.prepend('elm', elm)
environment.loaders.prepend('erb', erb)
environment.loaders.prepend('coffee', coffee)
environment.loaders.prepend('svelte', svelte)
module.exports = environment
